### PR TITLE
bump s3-files

### PR DESCRIPTION
**Pull request by tarunrajput**

### CODE REVIEW

**Comment by tarunrajput** [comment]
@orangewise , mind taking a look?

**Comment by ydemchuk-ivy** [comment]
@orangewise I would appreciate if we update aws-sdk to v3 as it produces the following warning on every project start

```
(node:15872) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
```

**Comment by orangewise** [comment]
Thanks for the PR. I'm willing to merge but currently the tests are failing:

npm t              

> s3-zip@3.3.0 test
> standard && tap --cov test/test*.js

​ FAIL ​ test/test-s3-same-file-alt-names.js
 ✖ self.s3.getObject is not a function

  node_modules/s3-files/s3-files.js                                     
  52 |     // console.log('->file', file);                              
  53 |     const params = { Bucket: self.bucket, Key: file }            
> 54 |     const s3File = self.s3.getObject(params).createReadStream()  
     | ---------------------------^                                     
  55 |                                                                  
  56 |     s3File.pipe(                                                 
  57 |       concat(function buffersEmit (buffer) {                     

  test: TAP
  stack: >
    StreamArray.<anonymous> (node_modules/s3-files/s3-files.js:54:28)

**Comment by tarunrajput** [comment]
> Thanks for the PR. I'm willing to merge but currently the tests are failing:
> 
> npm t
> 
> > s3-zip@3.3.0 test
> > standard && tap --cov test/test*.js
> 
> ​ FAIL ​ test/test-s3-same-file-alt-names.js ✖ self.s3.getObject is not a function
> 
> node_modules/s3-files/s3-files.js 52 | // console.log('->file', file); 53 | const params = { Bucket: self.bucket, Key: file }
> 
> > 54 |     const s3File = self.s3.getObject(params).createReadStream()
> > | ---------------------------^
> > 55 |
> > 56 |     s3File.pipe(
> > 57 |       concat(function buffersEmit (buffer) {
> 
> test: TAP stack: > StreamArray. (node_modules/s3-files/s3-files.js:54:28)

oops, sorry for the oversight! I've fixed the tests and also submitted a patch PR to s3-files (https://github.com/orangewise/s3-files/pull/24/files)
Suites

**Comment by orangewise** [comment]
Hi @tarunrajput, thanks again. This test is failing: 

  🌈 SUMMARY RESULTS 🌈  
                         
​ FAIL ​ test/test-s3-same-file-alt-names.js 1 failed of 3 697.855ms
 ✖ getaddrinfo ENOTFOUND bucket.s3.region.amazonaws.com

Can you please check?

Thanks!

**Comment by orangewise** [comment]
Would like to merge this but lack the time for fixing the code. Can you help me @tarunrajput?

**Comment by tarunrajput** [comment]
@orangewise , tests should pass now 😄
image

**Comment by mattpmoreno** [comment]
@tarunrajput thanks for putting in the work to get this done. @orangewise anything else we need to push this to the finish line? It would be great to bump this to AWS SDK v3

**Comment by orangewise** [comment]
Thanks @tarunrajput, merged and published. Sorry for the delay... Have a nice weekend!

**Pull request merged**
