### PR TITLE
update to use scope variables

### PR DESCRIPTION
**Pull request by negherbon**
With ES6+ we have more power about context and new great features, so i made a little upgrade :)

### CODE REVIEW

**Comment by negherbon** [comment]
i need merge this https://github.com/orangewise/s3-zip/pull/43 first

**Comment by negherbon** [comment]
@orangewise can you review please?

**Comment by orangewise** [comment]
Thanks man 👍

**Comment by orangewise** [comment]
Both your PRs have been merged, version 2.0.0 and 2.0.1 published...

**Comment by negherbon** [comment]
@orangewise thanks :)

**Pull request merged**
