### PR TITLE
Added option to preserve folder structure

### PR DESCRIPTION
**Pull request by rutkowskib**
Pull request from https://github.com/orangewise/s3-files/pull/12 has to be accepted to make changes work

### CODE REVIEW

**Comment by orangewise** [comment]
Hi @rutkowskib, can you also try to fix the failing tests?

**Comment by rutkowskib** [comment]
Tests are failing because i am trying to use version of s3-files which doesn't exist yet. You have to accept  orangewise/s3-files#12 first

**Comment by orangewise** [comment]
Ok, done.

**Comment by rutkowskib** [comment]
I think you have to publish on npm s3-files new version as well.

**Comment by orangewise** [comment]
@rutkowskib  I've released version 0.1.0, thank you for your contribution!

**Pull request merged**
